spring:
  application:
    name: test
server:
  port: 9999
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://node1:8100/eureka/
data:
  message: bcd
      
